name: Digital Writers Teview
favicon: null
layout_spectrum: 0.44808135367929935
typography_spectrum: 0.8774546107742935
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.611742947017774
  lightness: 0.5717229021247476
  saturation: 0.14268362778238952
  rhythmicContrast: 0.1624363011214882
purpose: []
